[package]
name = "basic-cli"
version = "0.1.0"
type = "platform"
spore-version = ">=0.1.0"

[platform]
contract-module = "platform_contract"
startup-contract = "main"
adapter-function = "main_for_host"
handled-effects = ["Console", "FileRead", "FileWrite", "Env", "Spawn", "Exit"]

[capabilities]
allow = ["Compute"]

[dependencies]
